name: mobile
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_dotenv: ^5.0.2
  flutter_form_builder: ^7.0.0
  flutter_hooks: ^0.18.1
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.0.8
  form_builder_validators: ^7.2.0
  freezed_annotation: ^1.1.0
  go_router: ^3.1.0
  json_annotation: ^4.4.0
  loading_indicator: ^3.0.2
  provider: ^6.0.2
  shimmer_animation: ^2.1.0+1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_gen_runner: ^4.1.3
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  go_router_builder: ^1.0.3
  injectable_generator: ^1.5.2
  json_serializable: ^6.1.3

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/

flutter_intl:
  enabled: true

dependency_overrides:
  intl: 0.17.0

flutter_gen:
  integrations:
    flutter_svg: true